---
fixtures:
  repositories:
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7
      branch: master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    stdlib: "https://github.com/simp/puppetlabs-stdlib.git"
    simplib: "https://github.com/simp/pupmod-simp-simplib.git"
    simp_banners: "https://github.com/simp/pupmod-simp-simp_banners"
  symlinks:
    issue: "#{source_dir}"
